### ISSUE TITLE
Get 0 for OTP

### ISSUE THREAD

**Issue by bkowald** [gbraad/gauth#100]
I get 0 for an OTP with a manual entry key of KN2XAZLSKNSWG4TFORFWK6KHN5SXGSDFOJSQ. This is locally using the Chrome extension. It works on your hosted site: https://chakradeo.net/otp/

**Comment by gbraad** [comment]
> https://chakradeo.net/otp/

This is not hosted by me

**Comment by gbraad** [comment]
Site has been republished with the latest code...
