### ISSUE TITLE
Also getting 0 

### ISSUE THREAD

**Issue by netluxe** [gbraad/gauth#101]
I'm also getting a 0 (this was on a test addition of an amazon.com account, setting up 2FA on it [it works on the official google authenticator iOS app and another chrome addon] - using the web version hosted on your URL https://gauth.apps.gbraad.nl ).  

Not noticing the ability to scan the generated QR code, but even adding the key manually (following the instructions to the T), whether spaces or no spaces in the key, will result in the account being added but showing a 0, even after the timer has reset the TOTP/OTP code is still showing as 0.

**Comment by gbraad** [comment]
It seems something got changed in a number of digits a secret provided by
Amazon contains. Might look into this...

**Comment by netluxe** [comment]
I should note here, after checking the additional posts listed under the issues, there seems to be an issue that perhaps may be related to the fact that the one hosted at the URL of this repository's creator on his webspace, is actually not up-to-date with the most recent/working version of the code base, as I received a working & accurate (double-checked with my other devices using the same key/account) on the URL listed in this post:

https://github.com/gbraad/gauth/issues/99

**Just seeing your reply now, Gerard, on my posting this update.  I should note that it works on the following URL from the above linked post:**

https://chakradeo.net/otp 

Entering the key code there will display it properly.  Strange.

**Comment by gbraad** [comment]
Site has been republished with the latest code...
