### ISSUE TITLE
Setting up Google Authenticator on desktop

### ISSUE THREAD

**Issue by SmedleyJ** [gbraad/gauth#102]
I'm having difficulty setting up Authenticator on desktop.  I already have on my phone with acct I set up by scanning the code.  How do I get the "secret code" to set up my desktop?  I've tried a new OTP on the site I'm trying to access.

Smedmail@kc.rr.com

**Comment by ajostergaard** [comment]
You have to use the same code/secret/qr in all your token 'wallets'.

Are you getting an error?

**Comment by SmedleyJ** [comment]
Well, I can’t get the site to accept from the desktop, only the phone app.   I guess I don’t understand what this secret code is and where I find it.  Is it one of my 10 eight digit back-up codes?

Appreciate any advise you can offer.

Thank you,

SmedleyJ

**Comment by gbraad** [comment]
I am slightly confused about the steps taken, but the secret would have to be shared between your phone and the desktop. They would have to generate the same secret response. This is needed, as none of the service providers will issue more than one OTP (2FA) option.

The code that is needed is a 16, 20 or 32 digit long code, that is used to generate the tokens. It was either provided to you as a QR code, or as a string of characters.

**Comment by SmedleyJ** [comment]
Oh, I don’t think I kept the code.  Is it retrievable from my phone app?  Or do I need to disable OTP on the site and re-initiate?  If so do I run any risks in not being able to get into the site?

Thanks,

**Comment by gbraad** [comment]
ALWAYS keep a papercopy of the code. You do not want to go through the process of having to request a reset from the service provider. I have had this experience, which depends on the service provider, but some make it very difficult. For instance, Amazon AWS wants you to verify your living address and requests you to hand over proof of residence, while for some... it is just a minor click of a button... maybe followed by a password reset.

You should always be able to remove the 2FA-enabled state on any of these websites, as this is also the way you have to transfer (register) a new device. When you remove the option, just re-enable and you will follow the same process as before. If you are handed a QR-code, save the image somewhere safe (print it), and look for the manual input option, and also save this code (they match, but the manual format is easier to handle IMO). You can rescan the QR code with your phone, and enter the code also in the desktop side. They should both generate the same responses. If so, you can continue.

If for some reason you can not get the information from the QR code in a manual entering form, you can use an online QR code reading page, to extract the information.
