### ISSUE TITLE
all my keys have disappeared 

### ISSUE THREAD

**Issue by pain49** [gbraad/gauth#107]
hi there today i just noticed that all my keys have been vanished idk why , is there any method to recover them ?

**Comment by Chandrian** [comment]
All my keys disappeared today ....................

**Comment by Chandrian** [comment]
Good to know, but how can I get someone else keys then? About Alice@google.com?

**Comment by gbraad** [comment]
Alice@google.com is the initial key. It is a demonstration entry that is
used when no config exists.
This was also there when you first started the application...

**Comment by gbraad** [comment]
> alice@google.com

https://github.com/gbraad/gauth/blob/470f22f061ea213c43f2df15ab90fc9e5b9b77a2/js/gauth.js#L131

**Comment by Chandrian** [comment]
Perfect, thank you. It makes sense!

Sorry!
