### ISSUE TITLE
2FA Codes are returning incorrect numbers

### ISSUE THREAD

**Issue by viniciussvl** [gbraad/gauth#111]
Hello, I have always used gauth in chrome and now it is behaving strangely, I put the same Secret Key both in gauth and google authenticator (android) and in gauth it returns me a totally incorrect 2fa, already in android the same secret key returns the correct 2fa. What could be happening? I've done everything, deleted the ga secrets, put the backups and nothing ...

**Comment by ajostergaard** [comment]
Is the time and date on your PC correct?

**Comment by viniciussvl** [comment]
No, they were wrong. Thank you very much.
No, they were wrong. Thank you very much!

**Comment by ajostergaard** [comment]
:) Don't forget to close the issue if its resolved.
