### ISSUE TITLE
Import Option

### ISSUE THREAD

**Issue by davchana** [gbraad/gauth#112]
Hi, great work.

Could you please add an textbox or something, where we could paste the app's exported json and also data from other apps in the same your-app-json schema, to quickly mass import the accounts & keys?

I changed phones, & use Google Auth. I have already saved all QR codes & keys as & when I activated them, about 20.

**Comment by alex-moreno** [comment]
same request, how do you import your backed up data back into the app?

**Comment by greggles** [comment]
@davchana I provided some instructions at https://github.com/gbraad/gauth/issues/113 Maybe you already knew that, but in case not, now you've got them.

**Comment by gbraad** [comment]
it is just a text file with a particular format... open with notepad, text edit or whatever you machine/phone provides to open txt files with.

note: the format is called json and it contains a collection (array) of values in a the combination of key-value (name, secret).
