### ISSUE TITLE
GAuth icon is missing

### ISSUE THREAD

**Issue by ofirz** [gbraad/gauth#51]
Today the GAuth icon disappeared, and instead I get the common-looking Firefox Marketplace in the taskbar and in the window icon.

This is most likely the result of updating to Firefox 34.0.5, but FYI, the following image link is broken:
<link rel="apple-touch-icon" href="img/icon-48.png" /> 

See screenshot:

![gauth-missing-icon](https://cloud.githubusercontent.com/assets/408956/5448632/11afb38c-8499-11e4-9290-a3c63921e13e.png)

**Comment by iiro** [comment]
Sorry about this - but I even cannot find the icon from Chrome... Not related probably but... I'm confused how to launch the app.

**Comment by gbraad** [comment]
I have updated the icons and removed some of the unused formats. I tested it on a Flame running 2.0 and 2.2 and inside the emulator. Next up is to test it on Windows and Android. I would appreciate if you could retry this...

**Comment by ofirz** [comment]
Hi, Gerard,

Thanks for the update. I uninstalled GAuth and reinstalled it to no avail. I can see the new icon (congrats, it's smart!) but unfortunately I don't get it. What I did instead was try to install "Mixcloud", another app from the Firefox marketplace. Take a look at the attached image - for the Mixcloud app, the icon got installed correctly. So may you can take a look at their app definition to see how they provided the icon? 

Thanks for the support,

Ofir


![gauth-icon](https://cloud.githubusercontent.com/assets/408956/5635009/f7f44266-9599-11e4-8cc8-6cdbfd77243f.png)

**Comment by gbraad** [comment]
Thanks for helping out on this... but I guess this is almost an issue with Firefox itself as I can not see the icon for installation. But yet it is there for the launcher. I will reach out to Mozilla and see if the Marketplace can help.

![mixcloud](https://cloud.githubusercontent.com/assets/1894/5641672/6bdee350-9678-11e4-862e-71e77cbb5cbc.png)

**Comment by gbraad** [comment]
Again pushed a manifest.webapp in which 16x16 and 48x48 are also defined.

**Comment by ofirz** [comment]
Gerard,

During the installation - the icon is always showing the "Firefox
Marketplace" at the top, as you presented in the recent snapshot. However,
after the installation, the "Mixcloud" app gets its original icon, while
the GAuth does not.

Please note I tested this on another Windows 7 64bit machine with FF 34.0.5
and got the same result.

Ofir


On Tue, Jan 6, 2015 at 10:23 PM, Gerard Braad — 吉拉德 <
notifications@github.com> wrote:

> Thanks for helping out on this... but I guess this is almost an issue with
> Firefox itself as I can not see the icon for installation. But yet it is
> there for the launcher. I will reach out to Mozilla and see if the
> Marketplace can help.
>
> [image: mixcloud]
> <https://cloud.githubusercontent.com/assets/1894/5641672/6bdee350-9678-11e4-862e-71e77cbb5cbc.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gbraad/html5-google-authenticator/issues/51#issuecomment-68983789>
> .
>



-- 
*Ofir Zwebner *| ofir@houzz.com

**Comment by gbraad** [comment]
Reported: https://bugzilla.mozilla.org/show_bug.cgi?id=1118649

**Comment by gbraad** [comment]
@ofirz Any change?
@iiro https://chrome.google.com/webstore/detail/gauth-authenticator-hoste/jcmgkikfgdbehjdajjdnebnnmmknfblm an alternative installation is possible for Chrome users

**Comment by ofirz** [comment]
Hi Gerard,

Sorry for the late reply.

Congrats for new L&F for the app, looks much better. The Mozilla has not
been changed, something is still missing with the icon.

I did get the Chrome app and will stick to it - thanks for making it work!
I think I will stick to that one and let the Mozilla one go for now. If you
need me to test again when you launch a new version I'd be happy to.

I suggest that, on the Chrome store, under "website", you should link to
your own website, or to Github (
https://github.com/gbraad/html5-google-authenticator), not to the online
version of the tool (http://gauth.apps.gbraad.nl/).

I wanted to make a modest donation but I'm not familiar with Flattr and
Gratipay. If you have a paypal please let me know. I think you should have
those options available in the About section of the app.

Thanks,

Ofir










On Sat, Jan 17, 2015 at 8:12 AM, Gerard Braad — 吉拉德 <
notifications@github.com> wrote:

> @ofirz <https://github.com/ofirz> Any change?
> @iiro <https://github.com/iiro>
> https://chrome.google.com/webstore/detail/gauth-authenticator-hoste/jcmgkikfgdbehjdajjdnebnnmmknfblm
> an alternative installation is possible for Chrome users
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gbraad/html5-google-authenticator/issues/51#issuecomment-70372483>
> .
>



-- 
*Ofir Zwebner *| ofir@houzz.com

**Comment by ofirz** [comment]
Please notice bug when entering new authentication (occurs on the Chrome
application) -

Click on "Add" to add a new key
Type something in Account Name, then type secret key, then click on Account
Name to edit it, or anywhere else in the dialog
Result: the fields get cleared and the account gets created; this should
only happen when you explicitly click on the "Add" button.

O

On Wed, Jan 21, 2015 at 1:08 PM, Ofir Zwebner <ofir@houzz.com> wrote:

> Hi Gerard,
>
> Sorry for the late reply.
>
> Congrats for new L&F for the app, looks much better. The Mozilla has not
> been changed, something is still missing with the icon.
>
> I did get the Chrome app and will stick to it - thanks for making it work!
> I think I will stick to that one and let the Mozilla one go for now. If you
> need me to test again when you launch a new version I'd be happy to.
>
> I suggest that, on the Chrome store, under "website", you should link to
> your own website, or to Github (
> https://github.com/gbraad/html5-google-authenticator), not to the online
> version of the tool (http://gauth.apps.gbraad.nl/).
>
> I wanted to make a modest donation but I'm not familiar with Flattr and
> Gratipay. If you have a paypal please let me know. I think you should have
> those options available in the About section of the app.
>
> Thanks,
>
> Ofir
>
>
>
>
>
>
>
>
>
>
> On Sat, Jan 17, 2015 at 8:12 AM, Gerard Braad — 吉拉德 <
> notifications@github.com> wrote:
>
>> @ofirz <https://github.com/ofirz> Any change?
>> @iiro <https://github.com/iiro>
>> https://chrome.google.com/webstore/detail/gauth-authenticator-hoste/jcmgkikfgdbehjdajjdnebnnmmknfblm
>> an alternative installation is possible for Chrome users
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/gbraad/html5-google-authenticator/issues/51#issuecomment-70372483>
>> .
>>
>
>
>
> --
> *Ofir Zwebner *| ofir@houzz.com
>
>
>
>


-- 
*Ofir Zwebner *| ofir@houzz.com

**Comment by ofirz** [comment]
Another usability issue for your consideration -

Please allow to highlight the authentication number so one could mark it
and copy it, or better - support a copy to clipboard (
http://stackoverflow.com/questions/7144702/the-proper-use-of-execcommandpaste-in-a-chrome-extension/7147192#7147192)
which would really be sweet.

Ofir


On Thu, Jan 22, 2015 at 11:24 AM, Ofir Zwebner <ofir@houzz.com> wrote:

> Please notice bug when entering new authentication (occurs on the Chrome
> application) -
>
> Click on "Add" to add a new key
> Type something in Account Name, then type secret key, then click on
> Account Name to edit it, or anywhere else in the dialog
> Result: the fields get cleared and the account gets created; this should
> only happen when you explicitly click on the "Add" button.
>
> O
>
> On Wed, Jan 21, 2015 at 1:08 PM, Ofir Zwebner <ofir@houzz.com> wrote:
>
>> Hi Gerard,
>>
>> Sorry for the late reply.
>>
>> Congrats for new L&F for the app, looks much better. The Mozilla has not
>> been changed, something is still missing with the icon.
>>
>> I did get the Chrome app and will stick to it - thanks for making it
>> work! I think I will stick to that one and let the Mozilla one go for now.
>> If you need me to test again when you launch a new version I'd be happy to.
>>
>> I suggest that, on the Chrome store, under "website", you should link to
>> your own website, or to Github (
>> https://github.com/gbraad/html5-google-authenticator), not to the online
>> version of the tool (http://gauth.apps.gbraad.nl/).
>>
>> I wanted to make a modest donation but I'm not familiar with Flattr and
>> Gratipay. If you have a paypal please let me know. I think you should have
>> those options available in the About section of the app.
>>
>> Thanks,
>>
>> Ofir
>>
>>
>>
>>
>>
>>
>>
>>
>>
>>
>> On Sat, Jan 17, 2015 at 8:12 AM, Gerard Braad — 吉拉德 <
>> notifications@github.com> wrote:
>>
>>> @ofirz <https://github.com/ofirz> Any change?
>>> @iiro <https://github.com/iiro>
>>> https://chrome.google.com/webstore/detail/gauth-authenticator-hoste/jcmgkikfgdbehjdajjdnebnnmmknfblm
>>> an alternative installation is possible for Chrome users
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/gbraad/html5-google-authenticator/issues/51#issuecomment-70372483>
>>> .
>>>
>>
>>
>>
>> --
>> *Ofir Zwebner *| ofir@houzz.com
>>
>>
>>
>>
>
>
> --
> *Ofir Zwebner *| ofir@houzz.com
>
>
>
>


-- 
*Ofir Zwebner *| ofir@houzz.com

**Comment by gbraad** [comment]
@ofirz I added a donation option for Paypal to the source code README.md. I believe this option should not be in the about page... as donation is purely an option and not something I really want to promote. But yes, many people have requested this.

also, the clipboard option will follow. I am still not happy about the possible implementations... however, when I offer an option to hide the keys on the mainpage I want the user to either use a detailspage to see the generated secret by clicking... or avoid the details page and copy directly to clipboard instead. This is currently the idea...
