### ISSUE TITLE
Bug: Update not successful on Firefox Desktop App

### ISSUE THREAD

**Issue by stephenjudge** [gbraad/gauth#59]
I received a prompt when loading GAuth Authenticator on my Windows desktop, to upgrade to the latest version of the app. I clicked Yes, the app reloaded but it is now stuck on a loading screen. I can't access my 2FA codes now. Can a fix be issued for this? I am running Firefox 35 on Windows 7.

**Comment by gbraad** [comment]
You have to close the tab and reload the page (or restart Firefox). This
seems to be affecting users of Firefox since version 34 and it not
something I can fix on my end.

This error never occurred for me in Firefox 33, but always in Firefox 34
(even Developer Edition).

On Thu, Jan 15, 2015 at 10:40 PM, Stephen Judge <notifications@github.com>
wrote:

> I received a prompt when loading GAuth Authenticator on my Windows
> desktop, to upgrade to the latest version of the app. I clicked Yes, the
> app reloaded but it is now stuck on a loading screen. I can't access my 2FA
> codes now. Can a fix be issued for this? I am running Firefox 35 on Windows
> 7.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gbraad/html5-google-authenticator/issues/59>.
>



-- 
Gerard Braad — 吉拉德
   F/OSS & IT Consultant in Beijing
   http://gbraad.nl  gpg: 0x592CFE75

**Comment by stephenjudge** [comment]
I installed GAuth Authenticator as a desktop app from the Mozilla Marketplace, so I don't use it as the web version directly in Firefox. Anyway, I got another update prompt the other day, I accepted the update, left it open for an hour, then closed it, also closed Firefox. I relaunched GAuth Authenticator and Firefox, unfortunately nothing changed, it's still stuck on the loading screen. Is there even a way to grab a list of the accounts I was using GAuth Authenticator for. If I could even get that I'll just re-install GAuth Authenticator and start over. The problem is I can't even remember all the accounts I had 2FA setup for, and some of them I know don't even have an account recovery option with my 2FA code.

**Comment by gbraad** [comment]
If you have installed it on your desktop, you can retrieve the information
as described in #49;
https://github.com/gbraad/html5-google-authenticator/issues/49

sqlite3 $HOME/.gauthauthenticator-*/*.default/webappsstore.sqlite
'select * from webappsstore2;'



I do believe this is an issue with the way Firefox handles updates to
Application Cache. I wish I could assist you more...

**Comment by gbraad** [comment]
Desktop installations are not supported anymore by Firefox. Closing
