### ISSUE TITLE
Export Keys Failure

### ISSUE THREAD

**Issue by patinthehat** [gbraad/gauth#71]
Using the chrome extension, the export keys option fails to export the keys.  Nothing happens.
Environment: Ubuntu x64 14.04 / XFCE4 , Chromium 40.0.2214.111

It DOES work when hosted on apache and opened normally using chrome, the export process is only failing in the extension.

**Comment by gbraad** [comment]
This probably has to do with permission that need to be set in the wrapper; https://github.com/gbraad/chrome-gauth

**Comment by gbraad** [comment]
Fixed
