### ISSUE TITLE
You use TOTP...

### ISSUE THREAD

**Issue by rugk** [gbraad/gauth#73]
Your documentation states at some points different things. Often it only says [HOTP] (https://en.wikipedia.org/wiki/HMAC-based_One-time_Password_Algorithm) is used.
However to be more exactly you use [TOTP] (https://en.wikipedia.org/wiki/Time-based_One-time_Password_Algorithm).
TOTP is a variant of HOTP. So maybe you should clarify this on the sites where it is stated.
I already edited the wiki a bit to make this sure.

**Comment by rugk** [comment]
Is it fixed?

**Comment by gbraad** [comment]
No documentation or code I wrote mentioned HOTP.

**Comment by gbraad** [comment]
https://github.com/gbraad/gauth/blob/master/README.md

**Comment by rugk** [comment]
Ah you've changed it: https://github.com/gbraad/gauth/commit/91b4da95fc540710a647a91914ace7b34b0b87c2

Okay.

**Comment by rugk** [comment]
fixed by https://github.com/gbraad/gauth/commit/91b4da95fc540710a647a91914ace7b34b0b87c2
