### ISSUE TITLE
"Add" key button does not show up in app installed via the Mozilla Marketplace

### ISSUE THREAD

**Issue by ahx** [gbraad/gauth#77]
When using the app via the [url](http://gauth.apps.gbraad.nl) on Firefox for Android, the "Add" key button is shown after clicking the :pencil2: icon, but it does not show up when running the app installed via the Mozilla Marketplace.

I am running Firefox 34.0.1 on Android 4.2.2 on an old Fairphone.

**Comment by gbraad** [comment]
can you include a screenshot?

**Comment by ahx** [comment]
![screenshot_2015-08-21-13-33-32 copy](https://cloud.githubusercontent.com/assets/8669/9407637/839d534c-480b-11e5-9eda-e4f7e59d0093.png)

At first I thought, that this is an issue with my touchscreen, but as described above if accessed via the browser, it works as expected.

**Comment by gbraad** [comment]
Thanks, the screenshot makes it a whole lot clearer. I thought it did move to the new screen, but it doesn't. This sounds a lot like an older issue. Have you updated the application from Firefox? You can do this from the menu as Tools->Apps and do a "Check for Updates". it should inform you about an update for gauth and will trigger you to install/replace the needed apk on Android.

**Comment by ahx** [comment]
Thanks for the reply. Yes, I have tried that. – "No updates available". This should work without having the Google Play Store installed, right? Any more hints? – If not, I'll try to export the keys, re-install the gauth app and import the keys. Sounds like a good plan?

**Comment by gbraad** [comment]
Correct, Google play is not needed.
If you can export correctly it should already run a newer version of the
application.

Hmmmm... Can't seem to repro it here.

**Comment by ahx** [comment]
Hm… looks like I am stuck here. Nothing happens when I click on the "Export keys" button on the Settings page, but…
I have found it: I have remove the link from my homescreen, then start the app again from inside Firefox, this solved the issue. :hand:

**Comment by gbraad** [comment]
This confirms it was an old cached version. Glad it works now...
