### ISSUE TITLE
Infected?

### ISSUE THREAD

**Issue by jasonluttrell** [gbraad/gauth#78]
I tried forwarding the zipped file to a colleague and it was blocked by my email saying:

FILE DELETED

Microsoft Forefront Protection for Exchange Server removed a file since it was found to be infected.
File name: "gauth-master.zip"
Malware name: "ExceedinglyInfected"

**Comment by jasonluttrell** [comment]
Nevermind. It's on my end. Closing ticket.

**Comment by gbraad** [comment]
i am still curious what triggered Forefront to trigger this issue. And also, which gauth-master.zip you used; as from our releases or from your own generated zips?

**Comment by jasonluttrell** [comment]
Sorry, my bad. :) The issue was simply emailing the file as a Zip attachment in Outlook. It was the one from Github. I googled the issue and apparently some internal filters block certain files from being sent. It *assumes* it's a virus even though it's not. So, this has nothing to do with your files. It did seem like it at first though.
