### ISSUE TITLE
Deleting browsing history and cookies in Chrome results in a failure to load properly.

### ISSUE THREAD

**Issue by whatworx** [gbraad/gauth#82]
While trying to access my GitHub account using 2FA the package failed to load properly from within Chrome showing only a blank white screen as a result.  After some research I learned that clearing the browsing history and/or cookies will break the functionality and all the authentication information stored is inaccessible.

**Comment by gbraad** [comment]
Thanks for reporting this.

It seems to be the case, on almost any platform (besides mobile) that clearing cookies will also clear LocalStorage information. This can happen from tools like CCLeaner, but also from just the standard Chrome functionality.

Can you tell me which platform you were using?

Although the application was not originally written for use on desktop web browsers (aimed at mobile use), the more general usecase has been the usage from actually desktops. I think a message about this should be included in the README or application itself. Any suggestions?

**Comment by whatworx** [comment]
No problem.  I'm using Chrome (47.0.2526.73 beta-m) on Windows 7 Pro x64 sp1.  

A warning message the README is a great idea, and perhaps a banner notice within the GUI making users aware of the consequences should they consider clearing out their desktop browser cache.
