### ISSUE TITLE
Problem with Amazon secret keys

### ISSUE THREAD

**Issue by stephenjudge** [gbraad/gauth#87]
Amazon have recently enable 2FA. I was able to add my Amazon 2FA record to the Android FreeOTP app by scanning the barcode and it works fine. I then tried to manually and my Amazon account name an secret to GAuth on my desktop, but after I added it all I was getting was a 0 as the 2FA code. I copied the secret directly from the text displayed on Amazon for the manual add, as well as trying the secret extracted from the barcode, neither worked. Amazon's secrets are very long, 53 characters, so maybe this has something to do with it.

**Comment by gbraad** [comment]
TL;DR This might be a regression.

They have this feature already for quite a while and used to be one of the initial supported services. However recently I got a PR from an outsider contributor which could cause this issue. I might have to review this code in more detail and write a test.

**Comment by gbraad** [comment]
Does this issue still exist?

**Comment by gbraad** [comment]
Not reproducible.
