### ISSUE TITLE
Does not appear to work in Chromium.

### ISSUE THREAD

**Issue by absorber** [gbraad/gauth#88]
Chromium: Version 49.0.2623.108 Built on Ubuntu 14.04, running on LinuxMint 17.2 (64-bit)
Basically stays stuck like [this](http://i.imgur.com/OHr6Mew.png), even with all extensions off. I've tested it only from local storage though.

Console tells me:
```
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///home/me/sources/gauth/index.html' cannot be created in a document with origin 'null' and URL 'file:///home/me/sources/gauth/index.html'.
```

Firefox however (v45.0) seems to work like it should.

If any more information is required, I'm happy to provide :)

**Comment by gbraad** [comment]
Invalid. The application can not be opened using file://. The application needs to be served from http:// else Chrome will throw a security exception. Please use the included `node server.js` option or `python -m SimpleHTTPServer`.
