### ISSUE TITLE
Does not work after upgrade of FireFox 48.0

### ISSUE THREAD

**Issue by nilamdoc** [gbraad/gauth#93]
It has stopped working after FireFox auto upgraded itself.

**Comment by gbraad** [comment]
Hi,

thank you for the report, but I miss crucial information
Can you detail a little bit more about the setup?

  * Which platform?
  * Are you using the website or the extension?
  * Can you provide a screenshot?
  * Have you been able to reproduce this?
     * Close browser and redo the same steps...
     * If so, what can you see as error?  Ctrl+Shift+J to open the browser console
  * Do you have other extensions installed?

**Comment by gbraad** [comment]
https://github.com/gbraad/gauth/issues/89
