### ISSUE TITLE
What is secret key?

### ISSUE THREAD

**Issue by cameronroe** [gbraad/gauth#96]
Hi, I'm not sure how to use this. There are no instructions.

**Comment by gbraad** [comment]
I hope the service provider explains the procedure of setting up 2FA , and usually, this is the case. However, I have noticed that in recent time they seldom explain what needs to be done and just show a QR code. So first of, sorry for the lack of documentation...

The secret is a combination of numbers and characters that is provided to you as part of the 2FA process. This code is only shown once to you and is what is used to generate a response that changes automatically every 30 secs.

Something like the following image is provided
![](http://cdn.makeuseof.com/wp-content/uploads/2014/02/microsoft-2fa.jpg)

And in the case of GAuth, you have to use the "I'cant scan the bar code".
