### ISSUE TITLE
Unable to open in Waterfox

### ISSUE THREAD

**Issue by ArthurSCD** [gbraad/gauth#97]
Hello, 

For some time now I've been unable to open GAUTH in Waterfox (a 64 bit variant of Firefox). I've actually never encountered an addon that works for Firefox but won't work for Waterfox. 

Gauth also can't seem to detect Firefox at all, even though I also have firefox installed (which I did in hopes of re-accessing my GAUTH but still can't get it to work). 

GAUTH used to work on Waterfox but one day just stopped. 

Any advice or acknowledgement would be appreciated.
Thanks

**Comment by gbraad** [comment]
If this problem still exists, please reopen the issue.
