### ISSUE TITLE
Can't set PORT

### ISSUE THREAD

**Issue by Gribnif** [gbraad/gauth#98]
Attempts to set the PORT to anything but the default 6000 don't work. Other settings do change. Example:
`# gauth config:get PORT`
`6000`
`# gauth config:set PORT=4000`
`# gauth config:get PORT`
`6000`

I'm using release 1473047357.5d4763b.centos6 under Centos 7.2.1511.

**Comment by gbraad** [comment]
This configuration is not supported anymore as the RPM wrapper was a non-standard installer.
